Repository uriyyo/instapi, pull requests merged in 2019-09, with the labels that each got.

#18 🔨 Add Travis CI and Codecov integration
  .travis.yml
  codecov.yml
  setup.cfg
Labels: enhancement

#17 🍞 Refactor tests for models.comment
  tests/unit_tests/models/test_comments.py
Labels: test

#16 🍞 Add tests for models.user
  tests/unit_tests/models/conftest.py
  tests/unit_tests/models/test_user.py
Labels: test

#22 🔨 Add integration with Mergify
  .mergify.yml
Labels: enhancement, ready-to-merge

#23 🐛 Fix bug with Mergify label condition
  .mergify.yml
Labels: bug

#25 🍞 Add tests for a client
  tests/unit_tests/conftest.py
  tests/unit_tests/models/conftest.py
  tests/unit_tests/test_client.py
Labels: test

#27 🔨 Add integration with mypy
  .travis.yml
  instapi/client.py
  instapi/models/base.py
  instapi/models/comment.py
  instapi/models/feed.py
  instapi/models/resource.py
  instapi/models/user.py
  instapi/utils.py
  mypy.ini
  setup.cfg
Labels: enhancement

#28 🍞 Add tests for utils
  instapi/utils.py
  tests/unit_tests/conftest.py
  tests/unit_tests/models/conftest.py
  tests/unit_tests/models/test_user.py
  tests/unit_tests/test_utils.py
Labels: test

#30 📚 Add real-time information about Travis CI and Codecov
  README.md
Labels: documentation

#31 🍞 Add tests for models.base
  tests/unit_tests/models/test_base.py
Labels: test

#32 🐛 Add .coveragerc to exclude lines with # pragma: no cover comment
  .coveragerc
  instapi/models/comment.py
  instapi/models/user.py
Labels: bug

#33 Documentation/models.feed
  instapi/models/feed.py
Labels: documentation

#38 :book:Add docstrings for models.resource
  instapi/models/resource.py
Labels: documentation

#39 🎉 Import to instapi.__init__ all public things
  instapi/__init__.py
  instapi/models/__init__.py
Labels: enhancement

#40 ✨ Add more data for setup.py, remove setup.cfg
  setup.cfg
  setup.py
Labels: enhancement

#43 :hammer:Add logo
  README.md
  instapi_logo.svg
Labels: enhancement

#44 🍞 Add tests for models.resource
  instapi/models/resource.py
  tests/unit_tests/conftest.py
  tests/unit_tests/models/conftest.py
  tests/unit_tests/models/test_resource.py
Labels: test

#48 🔨 Add pre-commit hooks to run unit tests and mypy before push
  .pre-commit-config.yaml
  setup.py
Labels: enhancement

#49 :bread:Add tests for models.feed
  instapi/models/comment.py
  instapi/models/user.py
  tests/unit_tests/models/conftest.py
  tests/unit_tests/models/test_feed.py
Labels: test

#50 :tada:Update logo
  README.md
  instapi_logo.svg
  logo.svg
Labels: enhancement

#46 ✨ Add ability to automatically create random objects based on their classes
  tests/unit_tests/conftest.py
  tests/unit_tests/models/conftest.py
  tests/unit_tests/models/test_base.py
  tests/unit_tests/models/test_comments.py
  tests/unit_tests/models/test_resource.py
  tests/unit_tests/models/test_user.py
Labels: enhancement

#47 🔨 Move duplicated Resource creation logic to Resource class
  instapi/models/feed.py
  instapi/models/resource.py
  instapi/models/user.py
Labels: refactoring

#51 🐛 Fix broken after merge tests
  tests/unit_tests/models/conftest.py
  tests/unit_tests/models/test_feed.py
  tests/unit_tests/models/test_resource.py
Labels: bug

#53 🎉 Add ability to fetch media with different quality
  instapi/__init__.py
  instapi/models/__init__.py
  instapi/models/base.py
  instapi/models/resource.py
  tests/unit_tests/conftest.py
  tests/unit_tests/models/conftest.py
  tests/unit_tests/models/test_feed.py
  tests/unit_tests/models/test_resource.py
  tests/unit_tests/models/test_user.py
Labels: enhancement

#54 🍞 Refactor all tests due to latest updates
  instapi/models/base.py
  instapi/models/resource.py
  instapi/models/user.py
  tests/unit_tests/models/conftest.py
  tests/unit_tests/models/test_feed.py
  tests/unit_tests/models/test_resource.py
  tests/unit_tests/models/test_user.py
Labels: refactoring, test

#58 🐛 Fix bug
  instapi/models/base.py
  instapi/models/feed.py
Labels: bug

#61 🎉 Add ability to send direct messages
  instapi/__init__.py
  instapi/client.py
  instapi/client_api/__init__.py
  instapi/client_api/base.py
  instapi/client_api/client.py
  instapi/client_api/direct.py
  instapi/models/__init__.py
  instapi/models/base.py
  instapi/models/direct.py
  instapi/models/resource.py
  instapi/models/user.py
  instapi/types.py
  instapi/utils.py
  tests/unit_tests/client_api/__init__.py
  tests/unit_tests/client_api/test_base.py
  tests/unit_tests/client_api/test_direct.py
  tests/unit_tests/models/conftest.py
  tests/unit_tests/models/test_base.py
  tests/unit_tests/models/test_direct.py
  tests/unit_tests/test_utils.py
Labels: enhancement

#64 🎉 Add ability to send direct messages
  instapi/__init__.py
  instapi/client.py
  instapi/client_api/__init__.py
  instapi/client_api/base.py
  instapi/client_api/client.py
  instapi/client_api/direct.py
  instapi/models/__init__.py
  instapi/models/base.py
  instapi/models/direct.py
  instapi/models/resource.py
  instapi/models/user.py
  instapi/types.py
  instapi/utils.py
  tests/unit_tests/client_api/__init__.py
  tests/unit_tests/client_api/test_base.py
  tests/unit_tests/client_api/test_direct.py
  tests/unit_tests/models/conftest.py
  tests/unit_tests/models/test_base.py
  tests/unit_tests/models/test_direct.py
  tests/unit_tests/test_utils.py
Labels: enhancement

#60 Bugfix/limited accept negative numbers
  instapi/utils.py
  tests/unit_tests/test_utils.py
Labels: bug

#66 🔨 Add integration with isort and flake8
  .flake8
  .isort.cfg
  .pre-commit-config.yaml
  .travis.yml
  instapi/client.py
  instapi/client_api/base.py
  instapi/client_api/direct.py
  instapi/models/base.py
  instapi/models/direct.py
  instapi/models/feed.py
  instapi/models/resource.py
  instapi/models/user.py
  instapi/types.py
  instapi/utils.py
  mypy.ini
  setup.py
Labels: enhancement

#67 🎉 Use env variables as default credentials
  instapi/client.py
  tests/unit_tests/test_client.py
Labels: enhancement

#71 🎉 Add metaclass for autologging
  .isort.cfg
  instapi/__init__.py
  instapi/client.py
  instapi/models/__init__.py
  instapi/models/base.py
  instapi/utils/__init__.py
  instapi/utils/loggingmeta.py
  instapi/utils/utils.py
  setup.py
Labels: enhancement

#74 🎉 Add information about usertags to feeds
  instapi/models/feed.py
  tests/unit_tests/models/test_feed.py
Labels: enhancement
