Repository uriyyo/instapi, pull requests merged in 2019-08, with the labels that each got.

#1 :bug: Fix bug when Feed.liked_by always return False :bug:
  instapi/models/feed.py
Labels: bug

#8 Add tests for models.comment
  instapi/client.py
  pytest.ini
  setup.cfg
  tests/__init__.py
  tests/unit_tests/__init__.py
  tests/unit_tests/conftest.py
  tests/unit_tests/models/__init__.py
  tests/unit_tests/models/conftest.py
  tests/unit_tests/models/test_comments.py
Labels: test

#10 Create LICENSE
  LICENSE
Labels: documentation

#11 Master
  LICENSE
Labels: documentation

#12 🐛 Fix bug when limited call __next__ one extra time 🐛
  instapi/utils.py
Labels: bug
